binary_sensor:
  - platform: homeassistant
    id: outside_lights_state
    entity_id: light.outside_lights
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: outside_lights_button
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: garage_floor_lights_state
    entity_id: light.garage_floor_lights
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: garage_floor_lights_button
            state:
              checked: !lambda return x;

text_sensor:
  - platform: homeassistant
    id: external_garage_state
    entity_id: cover.external_garage
    on_value:
      then:
        - lvgl.label.update:
            id: external_garage_label
            text: !lambda |-
              return ("External Garage\n" + x).c_str();

  - platform: homeassistant
    id: internal_garage_state
    entity_id: cover.internal_garage
    on_value:
      then:
        - lvgl.label.update:
            id: internal_garage_label
            text: !lambda |-
              return ("Internal Garage\n" + x).c_str();

  - platform: homeassistant
    id: weather_state
    entity_id: weather.forecast_home
    on_value:
      then:
        - lvgl.label.update:
            id: weather_label
            text: !lambda |-
              return ("Weather: " + x).c_str();

sensor:
  - platform: homeassistant
    id: home_temperature
    entity_id: sensor.temp_presence_and_humidity_temperature
    on_value:
      then:
        - lvgl.label.update:
            id: home_temperature_label
            text:
              format: "Temp: %.1f°C"
              args: [ 'x' ]
